# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_emailverifyrecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/%Y/%m'),
        ),
    ]
