# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20170310_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('distance',), 'verbose_name': '位置', 'verbose_name_plural': '位置'},
        ),
        migrations.AlterField(
            model_name='house',
            name='device',
            field=models.ManyToManyField(blank=True, null=True, to='houses.Device', verbose_name='设施信息'),
        ),
    ]
