# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 23:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Appointment_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('appointment_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='预约时间')),
                ('house', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='operation_appointment_related', to='houses.House', verbose_name='住房')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='operation_appointment_related', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='operation_userfavorite_related', to='houses.House', verbose_name='住房')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='operation_userfavorite_related', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'abstract': False,
                'verbose_name_plural': '用户收藏',
            },
        ),
    ]
