# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 23:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from apps.houses.models import address_validate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20, verbose_name='城市名')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.SmallIntegerField(default='', primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=10, verbose_name='设备名')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, validators=[
                    address_validate], verbose_name='房源地址')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='简介')),
                ('detail', models.TextField(verbose_name='详情')),
                ('price', models.FloatField(verbose_name='出租价格')),
                ('house_show', models.ImageField(upload_to='house/%Y/%m', verbose_name='房源展示')),
                ('reservation', models.IntegerField(default=0, verbose_name='预约人数')),
                ('favorite_nums', models.IntegerField(default=0, verbose_name='感兴趣的人数')),
                ('house_type', models.CharField(max_length=20, verbose_name='户型')),
                ('rent_type', models.CharField(choices=[('whole', '整租'), ('share', '合租')], default='whole', max_length=10)),
                ('transport', models.CharField(max_length=50, verbose_name='交通状况')),
                ('device', models.ManyToManyField(to='houses.Device', verbose_name='设施信息')),
                ('landlord', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='房东')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(verbose_name='住房到学校的距离')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=20, verbose_name='附近学校名称')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='houses.City', verbose_name='学校所在城市')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.School'),
        ),
        migrations.AddField(
            model_name='house',
            name='school',
            field=models.ManyToManyField(through='houses.Position', to='houses.School', verbose_name='周边学校'),
        ),
    ]
