# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': '房源', 'verbose_name_plural': '房源'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '学校', 'verbose_name_plural': '学校'},
        ),
    ]
