# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-29 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20170412_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_front_image',
            field=models.ImageField(null=True, upload_to='school', verbose_name='学校风采'),
        ),
    ]
