# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-29 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_school_school_front_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='advantage',
            field=models.CharField(default='', max_length=80, verbose_name='学校的地理优势'),
        ),
    ]
