# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20170308_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '学校', 'verbose_name_plural': '学校'},
        ),
    ]
